use PracticeModule;


CREATE PROCEDURE empWithCommission
AS
BEGIN
    SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, COMMISSION_PCT
    FROM EMPLOYEES
    WHERE COMMISSION_PCT IS NOT NULL;
END;

EXEC empWithCommission ;